const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/product-1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/product-2.jpg',
      price: 200,
      countInStock: 14,
      brand: 'Adidas',
      rating: 4,
      numReviews: 13,
      description: 'High Quality Product',
    },
    {
      name: 'Lacoste Free Shirt',
      slug: 'lacoste-free-shirt',
      category: 'Shirts',
      image: '/images/product-3.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 5,
      numReviews: 4,
      description: 'High Quality Product',
    },
    {
      name: 'Nike Slim Pants',
      slug: 'nike-slim-pants',
      category: 'Pants',
      image: '/images/product-4.jpg',
      price: 130,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'High Quality Product',
    },
    {
      name: 'Puma Slim Pants',
      slug: 'puma-slim-pants',
      category: 'Pants',
      image: '/images/product-5.jpg',
      price: 65,
      countInStock: 20,
      brand: 'Puma',
      rating: 3,
      numReviews: 10,
      description: 'High Quality Product',
    },
    {
      name: 'Adidas Slim pants',
      slug: 'adidas-slim-pants',
      category: 'Pants ',
      image: '/images/product-6.jpg',
      price: 120,
      countInStock: 4,
      brand: 'Adidas',
      rating: 4,
      numReviews: 17,
      description: 'High Quality Product',
    },
  ],
};
export default data;
